export const GET_MARKERS_START = 'GET_MARKERS_START';
export const GET_MARKERS_SUCCESS = 'GET_MARKERS_SUCCESS';
export const GET_MARKERS_ERROR = 'GET_MARKERS_ERROR';

export const ADD_MARKER_START = 'ADD_MARKER_START';
export const ADD_MARKER_SUCCESS = 'ADD_MARKER_SUCCESS';
export const ADD_MARKER_ERROR = 'ADD_MARKER_ERROR';

export const GET_RESYCLE_TYPES_START = 'GET_RESYCLE_TYPES_START';
export const GET_RESYCLE_TYPES_SUCCESS = 'GET_RESYCLE_TYPES_SUCCESS';
export const GET_RESYCLE_TYPES_ERROR = 'GET_RESYCLE_TYPES_ERROR';
